Repository WPTT/WPThemeReview, pull requests merged in 2018-10, with the labels that each got.

#177 Ruleset: add the PHPCompatibilityWP standard
  README.md
  WPThemeReview/ruleset.xml
  composer.json
Labels: enhancement, pr: needs review

#180 Update for PHPCompatibility 9.0.0
  README.md
  composer.json
Labels: enhancement, pr: needs review

#182 Warn on empty statements
  WPThemeReview/ruleset.xml
Labels: enhancement, pr: needs review

#178 Issue template: textual update
  .github/ISSUE_TEMPLATE
Labels: pr: needs review

#183 Build/Travis: test builds against PHP 7.3
  .travis.yml
Labels: pr: needs review

#187 Autoload: bug fix
  autoload.php
Labels: issue: bug, pr: needs review

#186 Ruleset: bug fix
  WPThemeReview/ruleset.xml
Labels: issue: bug, pr: needs review

#176 Add contributing template
  .github/CONTRIBUTING.md
Labels: enhancement

#181 Feature/add changelog
  CHANGELOG.md
Labels: enhancement

#188 Release version 0.1.0
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE
  .travis.yml
  CHANGELOG.md
  README.md
  WPThemeReview/ruleset.xml
  autoload.php
  composer.json
Labels: meta, pr: needs review
