Repository WPTT/WPThemeReview, pull requests merged in 2018-06, with the labels that each got.

#156 Ruleset: bug fix - use the correct sniffname
  WordPress-Theme/ruleset.xml
Labels: high priority, issue: bug, pr: needs review

#150 Ruleset: treat all files as UTF-8
  WordPress-Theme/ruleset.xml
Labels: pr: needs review

#151 Prohibit PHP closing tag at end of PHP-only file
  WordPress-Theme/ruleset.xml
Labels: pr: needs review

#152 Warn on empty statements
  WordPress-Theme/ruleset.xml
Labels: pr: needs review

#153 Detect usage of deprecated WP classes and function call parameters
  WordPress-Theme/ruleset.xml
Labels: pr: needs review

#157 Add upstream DB related sniffs
  WordPress-Theme/ruleset.xml
Labels: enhancement, pr: needs review

#159 NoAddAdminPages: add `add_links_page()` to the functions list
  WordPress/Sniffs/Theme/NoAddAdminPagesSniff.php
  WordPress/Tests/Theme/NoAddAdminPagesUnitTest.inc
  WordPress/Tests/Theme/NoAddAdminPagesUnitTest.php
Labels: enhancement, pr: needs review

#160 Add sniffs to detect accessing session data
  WordPress-Theme/ruleset.xml
Labels: pr: needs review

#161 Add sniff to detect timezone changing
  WordPress-Theme/ruleset.xml
Labels: pr: needs review

#162 Add check for whitespace before PHP open tag
  WordPress-Theme/ruleset.xml
Labels: pr: needs review

#109 Feature/discouraged iframe
  WordPress/Sniffs/Theme/ForbiddenIframeSniff.php
  WordPress/Tests/Theme/ForbiddenIframeUnitTest.inc
  WordPress/Tests/Theme/ForbiddenIframeUnitTest.php
Labels: enhancement, pr: needs review
