Repository WPTT/WPThemeReview, pull requests merged in 2019-01, with the labels that each got.

#194 Update to WordPressCS 2.0.0
  .gitattributes
  .github/CONTRIBUTING.md
  .travis.yml
  Test/bootstrap.php
  WPThemeReview/Sniffs/CoreFunctionality/NoDeregisterCoreScriptSniff.php
  WPThemeReview/Sniffs/PluginTerritory/AdminBarRemovalSniff.php
  WPThemeReview/Sniffs/PluginTerritory/ForbiddenFunctionsSniff.php
  WPThemeReview/Sniffs/PluginTerritory/NoAddAdminPagesSniff.php
  WPThemeReview/Sniffs/PluginTerritory/SessionFunctionsUsageSniff.php
  WPThemeReview/Sniffs/Plugins/CorrectTGMPAVersionSniff.php
  WPThemeReview/ruleset.xml
  composer.json
  phpunit.xml.dist
Labels: meta, pr: needs review

#195 Minor readme changes
  README.md
Labels: enhancement

#196 Remove aliases reference from autoload
  .github/CONTRIBUTING.md
  WPThemeReview/ruleset.xml
  autoload.php
Labels: enhancement

#197 Bump suggested installer version
  README.md
  composer.json
Labels: pr: needs review
