Repository WPTT/WPThemeReview, pull requests merged in 2019-05, with the labels that each got.

#208 Feature/prefix globals warning
  WPThemeReview/Sniffs/CoreFunctionality/PrefixAllGlobalsSniff.php
  WPThemeReview/Tests/CoreFunctionality/PrefixAllGlobalsTests/attachment.inc
  WPThemeReview/Tests/CoreFunctionality/PrefixAllGlobalsTests/footer_widgets.inc
  WPThemeReview/Tests/CoreFunctionality/PrefixAllGlobalsTests/header.inc
  WPThemeReview/Tests/CoreFunctionality/PrefixAllGlobalsTests/page-recent-news.inc
  WPThemeReview/Tests/CoreFunctionality/PrefixAllGlobalsTests/page-templates/layouts/page_two-columns.inc
  WPThemeReview/Tests/CoreFunctionality/PrefixAllGlobalsTests/partials/post-edit.inc
  WPThemeReview/Tests/CoreFunctionality/PrefixAllGlobalsTests/social-share.inc
  WPThemeReview/Tests/CoreFunctionality/PrefixAllGlobalsUnitTest.inc
  WPThemeReview/Tests/CoreFunctionality/PrefixAllGlobalsUnitTest.php
  WPThemeReview/ruleset.xml
Labels: enhancement

#219 Add rule about setting INI during runtime in themes
  WPThemeReview/ruleset.xml
Labels: enhancement, pr: needs review

#221 Travis: remove `sudo: false`
  .travis.yml
Labels: pr: needs review

#220 Rulesets: Add XSD schema tags and validate rulesets against schema (PHPCS 3.2+/3.3.2+)
  .phpcs.xml.dist
  .travis.yml
  WPThemeReview/ruleset.xml
Labels: pr: needs review

#215 Add register block functions to forbidden functions sniff
  WPThemeReview/Sniffs/PluginTerritory/ForbiddenFunctionsSniff.php
  WPThemeReview/Tests/PluginTerritory/ForbiddenFunctionsUnitTest.inc
  WPThemeReview/Tests/PluginTerritory/ForbiddenFunctionsUnitTest.php
Labels: enhancement, pr: needs review

#217 Add deprecated parameter values rule in the ruleset
  WPThemeReview/ruleset.xml
Labels: enhancement, pr: needs review

#222 Update forbidden functionality with cron functions
  WPThemeReview/Sniffs/PluginTerritory/ForbiddenFunctionsSniff.php
  WPThemeReview/Tests/PluginTerritory/ForbiddenFunctionsUnitTest.inc
  WPThemeReview/Tests/PluginTerritory/ForbiddenFunctionsUnitTest.php
Labels: enhancement, pr: needs review

#223 Travis: run the code style related and ruleset checks in separate stages
  .travis.yml
Labels: pr: needs review
